simon = User.create!(email: 'simon@simon', password: '1234567')
gretchen = User.create!(email: 'gretchen@gretchen.com', password: '1234567')
hannah = User.create!(email: 'hannah@hannah.com', password: '1234567')
julia = User.create!(email: 'julia@julia.com', password: '1234567')
ruegan = User.create!(email: 'ruegan@ruegen.com', password: '1234567')
samantha = User.create!(email: 'samantha@samantha.com', password: '1234567')
bridget = User.create!(email: 'bridgette@bridgette.com', password: '1234567')
alex = User.create!(email: 'alex@alex.com', password: '1234567')

climber = GrowthFrom.create!(name: 'climber', description: '')
ferm = GrowthFrom.create!(name: 'fern', description: '')
aquatic = GrowthFrom.create!(name: 'aquatic', description: '')
grass = GrowthFrom.create!(name: 'grass', description: '')
herb = GrowthFrom.create!(name: 'herb', description: '')
shrub = GrowthFrom.create!(name: 'shrub', description: '')
small_tree = GrowthFrom.create!(name: 'small tree', description: '')
medium_tree = GrowthFrom.create!(name: 'medium tree', description: '')
large_tree = GrowthFrom.create!(name: 'large tree', description: '')